### PR TITLE
Split up windows jobs

### PR DESCRIPTION
**Pull request by bensze01**
Split up the windows tests into individual builds, and group them into ~20 minute sized chucks that share the checkout and python dependency installation steps

CI runs:
  - OpenCI:
    -  [mbedtls-release-ci-testing][1] (0eba489dca91876e976a0c00b65d523c868a7241)
    - PR-head
      - [development - good][3]
      - [mbedtls-2.28 - good][4]
      - [CMake fail][5]
  - Internal CI:
    - [mbedtls-release-ci-testing][2] (0eba489dca91876e976a0c00b65d523c868a7241)
    - PR-head
      - [development - good][6]
      - [mbedtls-2.28 - good][7]
      - [CMake fail][8]
  
[1]: https://mbedtls.trustedfirmware.org/blue/organizations/jenkins/mbedtls-release-ci-testing/detail/mbedtls-release-ci-testing/151/pipeline/
[2]: https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbedtls-release-ci-testing/detail/mbedtls-release-ci-testing/584/pipeline/
[3]: https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbed-tls-pr-ci-testing/detail/PR-906-head/93/pipeline
[4]: https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbed-tls-pr-ci-testing/detail/PR-850-head/2/pipeline
[5]: https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbed-tls-pr-ci-testing/detail/PR-759-head/2/pipeline
[6]: https://mbedtls.trustedfirmware.org/blue/organizations/jenkins/mbed-tls-restricted-pr-ci-testing/detail/PR-906-head/16/pipeline
[7]: https://mbedtls.trustedfirmware.org/blue/organizations/jenkins/mbed-tls-restricted-pr-ci-testing/detail/PR-850-head/9/pipeline
[8]: https://mbedtls.trustedfirmware.org/blue/organizations/jenkins/mbed-tls-restricted-pr-ci-testing/detail/PR-759-head/7/pipeline

### CODE REVIEW

**Review by daverodgman — APPROVED** [review]
A couple of very minor points. I don't know the Groovy side well enough to give a very detailed review but LGTM.

**Comment by gilles-peskine-arm** [comment]
About the appearance on Blue Ocean: do you have an example run with the whole CI including Linux and outcome analysis?

**Comment by bensze01** [comment]
@gilles-peskine-arm I've added some full PR-head runs to the PR description.

**Review by daverodgman — APPROVED** [review]

**Comment by daverodgman** [comment]
Note that we now have 25 Windows executors internally https://jira.arm.com/browse/OSSDEVOPS-9809

**Comment by daverodgman** [comment]
I've requested 25 executors for OpenCI

**Pull request merged**
