### PR TITLE
Remove cutoff for running nightly PR-merge jobs

### PR DESCRIPTION
**Pull request by bensze01**
Since we've removed most tests from PR-merge we can afford to run it for all open PRs.

Test runs:  
 - PR-merge:
   - [Internal][1]
   - [Open CI][2]
 - [PR-head][3]
 - [release][4]
 
[1]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-906-merge/117/
[2]: https://ci.staging.trustedfirmware.org/view/Mbed-TLS/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-906-merge/6/
[3]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/job/PR-906-head/55/
[4]: https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/489/console

### CODE REVIEW

**Review by gilles-peskine-arm — APPROVED** [review]
Looks good to me on the basis of reading the code.

Regarding testing, I'd like to have a run of other jobs, to check that the removed imports don't break those. I guess a release job and a pr-head job (on one of the CI infrastructures would be enough).

**Comment by bensze01** [comment]
The requested test runs:
 - [PR-head][3]
 - [release][4]
 
[3]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/job/PR-906-head/55/
[4]: https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/489/console

**Review by mpg — APPROVED** [review]
LGTM

**Comment by mpg** [comment]
All test runs have completed successfully.

**Pull request merged**
