### PR TITLE
Enable Windows tests on the Open CI

### PR DESCRIPTION
**Pull request by arthur-she**
Signed-off-by: Arthur She <arthur.she@linaro.org>

### CODE REVIEW

**Comment by bensze01** [comment]
#47 Needs to be merged before this PR, to fix MSVC Windows jobs.

**Review by bensze01 — APPROVED** [review]
Successful test run on the internal CI:  
https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-906-head/22/

Looks good to me.

**Comment by bensze01** [comment]
Successful (and deliberately failing) test runs on the OpenCI:
Mbed-TLS/mbedtls-restricted#759:  [head](https://ci.trustedfirmware.org/view/Mbed-TLS/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-759-head/2/), [merge](https://ci.trustedfirmware.org/view/Mbed-TLS/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-759-merge/2/)  
Mbed-TLS/mbedtls-restricted#850:  [head](https://ci.trustedfirmware.org/view/Mbed-TLS/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-850-head/1/), [merge](https://ci.trustedfirmware.org/view/Mbed-TLS/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-850-merge/1/)
Mbed-TLS/mbedtls-restricted#906:  [head](https://ci.trustedfirmware.org/view/Mbed-TLS/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-906-head/2/), [merge](https://ci.trustedfirmware.org/view/Mbed-TLS/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-906-merge/2/)

**Review by gilles-peskine-arm — APPROVED** [review]
The [CI runs](https://github.com/Mbed-TLS/mbedtls-test/pull/46#issuecomment-1248364758) look good to me.

**Pull request merged**
