### PR TITLE
Use version numbers in $OPENSSL and $GNUTLS variables; add OpenSSL 3.0 and 3.1

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Start using version numbers in $OPENSSL and $GNUTLS variables, e.g. `$OPENSSL_1`, `$OPENSSL_1_1` and `$OPENSSL_1_1_1` are OpenSSL 1.1.1a. This will allow `all.sh` to reference these versions.

Keep the old names `$OPENSSL_NEXT` etc. pointing to the same versions for backward compatibility: we don't want to break `all.sh` in branches of mbedtls we care about (`development`, `mbedtls-2.28`, as well as open pull requests to these branches and other work in progress). We won't change what these non-numbered variables point to, we'll gradually migrate away from them.

Remove GnuTLS 3.3.8 which was `GNUTLS_LEGACY` and replace GnuTLS 3.4.10 with 3.4.6 which has all the features we need and [one less bugfix](https://github.com/Mbed-TLS/mbedtls-test/pull/122/commits/46a206feb6a0ab89e70c87599dcc642ee4f05f8d)). See also [3.x](https://github.com/Mbed-TLS/mbedtls/pull/8121), [2.28](https://github.com/Mbed-TLS/mbedtls/pull/8122) removing the use of `GNUTLS_LEGACY`.

Add OpenSSL 3.0 (long-time support branch) and 3.1 (latest release at this time) so that we can [test with modern versions of OpenSSL](https://github.com/Mbed-TLS/mbedtls/issues/7350). (Newer GnuTLS may follow later.)

### Test runs

* 46a206feb6a0ab89e70c87599dcc642ee4f05f8d on `development`: https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/530/ → (a previous run almost passed but glitched during result analysis)
* 46a206feb6a0ab89e70c87599dcc642ee4f05f8d on `mbedtls-2.28`: https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/529/ → PASS
* 46a206feb6a0ab89e70c87599dcc642ee4f05f8d on https://github.com/Mbed-TLS/mbedtls/pull/8122 : https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/51/ → PASS
* 20fcf5d6e3d007c7fb57b9696be9c2dae64f6af1 on development: https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/55/ → 
* a455488a4200febdd5c22b5f8f7dc2eaadbebe07 on `development`: [OpenCI](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/91/) → PASS
* a455488a4200febdd5c22b5f8f7dc2eaadbebe07 on `mbedtls-2.28`: [Internal CI](https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/543/) → PASS

### CODE REVIEW

**Review by tgonzalezorlandoarm — CHANGES_REQUESTED** [review]

**Review by tgonzalezorlandoarm — APPROVED** [review]
LGTM

**Review by waleed-elmelegy-arm — APPROVED** [review]
LGTM

**Comment by mpg** [comment]
@gilles-peskine-arm This has had two approvals for a month. Is anything blocking this from being merged (like, more test runs needed) or was it simply forgotten because the labels not up to date?

**Comment by gilles-peskine-arm** [comment]
@mpg Thanks for the ping! It does look like this slipped through the cracks due to not having the “approved” label. Though we did pause merging while the release was imminent.

Since there was some merging in a Docker file, even without a conflict, I've kicked off a test job on each CI. If those pass, we can merge.

**Pull request merged**
