### PR TITLE
Update remaining instance of the Cause check

### PR DESCRIPTION
**Pull request by bensze01**
Follow up to #71.

Tests:
[Timer-triggered run](https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/437)
[Manual run](https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/438/)

### CODE REVIEW

**Review by gilles-peskine-arm — APPROVED** [review]
Makes sense to me following https://github.com/Mbed-TLS/mbedtls-test/pull/71#discussion_r1015340762

**Review by mpg — DISMISSED** [review]
LGTM

**Comment by mpg** [comment]
Does this need more testing (labeled needs-ci) or is it ready for merge?

**Comment by bensze01** [comment]
So, looks like the older version of `ParametrizedTimerTriggerCause` present on the internal jenkins [doesn't extend `TimerTriggerCause`](https://github.com/jenkinsci/parameterized-scheduler-plugin/commit/35c937fb6d17cabdac8d4c0337609e4144177a43). I'll have to update this PR.

**Comment by bensze01** [comment]
I've pushed a new commit + added test runs that show the patch is now working as intended.

**Review by gilles-peskine-arm — APPROVED** [review]
Looks plausible to me (which is as good as I can give).

**Review by paul-elliott-arm — APPROVED** [review]
Looks reasonable to me as well.

**Pull request merged**
